# Project: ProjetoCentroSaude

CC = gcc
CFLAGS = -Wall -o0 -g -o
TARGET = aed
FILES = src/medico.c src/utente.c

main:
	@echo "Compiling"
	cc $(FILES) src/main.c $(CFLAGS) $(TARGET)

clean:
	rm -r $(TARGET) *.o
